import { Activity, Habit, UserProfile, Workout } from "@/types";
export const user: UserProfile = { name: "Abhay", email: "abhay@example.com", goal: "Build muscle", experience: "Intermediate", trainingDays: 4, sessionLength: "60 minutes" };
export const workouts: Workout[] = [
  { id: "push", day: "Monday", name: "Push Day", muscles: "Chest · Shoulders · Triceps", duration: 60, exercises: 6 }, { id: "rest-1", day: "Tuesday", name: "Rest & Recover", muscles: "Mobility · Recovery", duration: 0, exercises: 0, status: "rest" }, { id: "pull", day: "Wednesday", name: "Pull Day", muscles: "Back · Biceps · Rear delts", duration: 55, exercises: 6 }, { id: "rest-2", day: "Thursday", name: "Rest & Recover", muscles: "Mobility · Recovery", duration: 0, exercises: 0, status: "rest" }, { id: "legs", day: "Friday", name: "Leg Day", muscles: "Quads · Glutes · Hamstrings", duration: 65, exercises: 7 }, { id: "upper", day: "Saturday", name: "Upper Body", muscles: "Chest · Back · Arms", duration: 50, exercises: 5 }, { id: "rest-3", day: "Sunday", name: "Rest & Recover", muscles: "Mobility · Recovery", duration: 0, exercises: 0, status: "rest" },
];
export const habits: Habit[] = [
  { id: "workout", name: "Workout", target: 1, unit: "session", value: 1, completed: true, icon: "dumbbell" }, { id: "steps", name: "10,000 Steps", target: 10000, unit: "steps", value: 7850, completed: false, icon: "footprints" }, { id: "water", name: "Drink 3L Water", target: 3, unit: "L", value: 2.1, completed: false, icon: "droplets" }, { id: "sleep", name: "Sleep 8 Hours", target: 8, unit: "hours", value: 8, completed: true, icon: "moon" }, { id: "protein", name: "Protein Goal", target: 160, unit: "g", value: 128, completed: false, icon: "beef" }, { id: "stretch", name: "Stretching", target: 10, unit: "min", value: 10, completed: true, icon: "accessibility" },
];
export const activity: Activity[] = [{ title: "Completed Push Day", detail: "6 exercises · 58 min", time: "Today", icon: "check" }, { title: "Hit 10,000 steps", detail: "Daily habit", time: "Yesterday", icon: "footprints" }, { title: "Bench Press personal best", detail: "62.5 kg × 8", time: "2 days ago", icon: "trophy" }];
export const weeklyActivity = [{ day: "Mon", value: 1 }, { day: "Tue", value: 0 }, { day: "Wed", value: 1 }, { day: "Thu", value: 1 }, { day: "Fri", value: 0 }, { day: "Sat", value: 1 }, { day: "Sun", value: 0 }];
export const volume = [{ week: "W1", value: 18000 }, { week: "W2", value: 20500 }, { week: "W3", value: 21200 }, { week: "W4", value: 23100 }];
